export const IS_LOADING = "IS_LOADING";
export const DELETE_SESSION = "DELETE_SESSION";
export const GET_SESSION_DETAILS = "GET_SESSION_DETAILS";
export const GET_SESSION_ATTENDANCES = "GET_SESSION_ATTENDANCES";
